//
// File generated by rootcint at Fri Apr 23 11:57:58 2004.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

#include "MatlabDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "RtypesImp.h"

#include "TVectorProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void TmxArray_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TmxArray_IsA(const void*);
   static void *new_TmxArray(void *p = 0);
   static void *newArray_TmxArray(Long_t size);
   static void delete_TmxArray(void *p);
   static void deleteArray_TmxArray(void *p);
   static void destruct_TmxArray(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const TmxArray*)
   {
      TmxArray *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("TmxArray", TmxArray::Class_Version(), "TmxArray.h", 30,
                  typeid(TmxArray), DefineBehavior(ptr, ptr),
                  &::TmxArray::Dictionary, &TmxArray_IsA, 0,
                  sizeof(TmxArray) );
      instance.SetNew(&new_TmxArray);
      instance.SetNewArray(&newArray_TmxArray);
      instance.SetDelete(&delete_TmxArray);
      instance.SetDeleteArray(&deleteArray_TmxArray);
      instance.SetDestructor(&destruct_TmxArray);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const TmxArray*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

namespace ROOT {
   void TMatlab_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TMatlab_IsA(const void*);
   static void *new_TMatlab(void *p = 0);
   static void *newArray_TMatlab(Long_t size);
   static void delete_TMatlab(void *p);
   static void deleteArray_TMatlab(void *p);
   static void destruct_TMatlab(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const TMatlab*)
   {
      TMatlab *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("TMatlab", TMatlab::Class_Version(), "TMatlab.h", 42,
                  typeid(TMatlab), DefineBehavior(ptr, ptr),
                  &::TMatlab::Dictionary, &TMatlab_IsA, 0,
                  sizeof(TMatlab) );
      instance.SetNew(&new_TMatlab);
      instance.SetNewArray(&newArray_TMatlab);
      instance.SetDelete(&delete_TMatlab);
      instance.SetDeleteArray(&deleteArray_TMatlab);
      instance.SetDestructor(&destruct_TMatlab);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const TMatlab*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *TmxArray::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TmxArray::Class_Name()
{
   return "TmxArray";
}

//______________________________________________________________________________
const char *TmxArray::ImplFileName()
{
   return ROOT::GenerateInitInstance((const TmxArray*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TmxArray::ImplFileLine()
{
   return ROOT::GenerateInitInstance((const TmxArray*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TmxArray::Dictionary()
{
   fgIsA = ROOT::GenerateInitInstance((const TmxArray*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TmxArray::Class()
{
   if (!fgIsA) fgIsA = ROOT::GenerateInitInstance((const TmxArray*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TMatlab::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TMatlab::Class_Name()
{
   return "TMatlab";
}

//______________________________________________________________________________
const char *TMatlab::ImplFileName()
{
   return ROOT::GenerateInitInstance((const TMatlab*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TMatlab::ImplFileLine()
{
   return ROOT::GenerateInitInstance((const TMatlab*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TMatlab::Dictionary()
{
   fgIsA = ROOT::GenerateInitInstance((const TMatlab*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TMatlab::Class()
{
   if (!fgIsA) fgIsA = ROOT::GenerateInitInstance((const TMatlab*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TMatlab::Streamer(TBuffer &R__b)
{
   // Stream an object of class TMatlab.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TQQObject::Streamer(R__b);
      R__b >> fEvalReturn;
      R__b.CheckByteCount(R__s, R__c, TMatlab::IsA());
   } else {
      R__c = R__b.WriteVersion(TMatlab::IsA(), kTRUE);
      TQQObject::Streamer(R__b);
      R__b << fEvalReturn;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TMatlab::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TMatlab.

      TClass *R__cl = TMatlab::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fEngine", &fEngine);
      R__insp.Inspect(R__cl, R__parent, "*fOutputBuffer", &fOutputBuffer);
      R__insp.Inspect(R__cl, R__parent, "fEvalReturn", &fEvalReturn);
      TQQObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TMatlab_IsA(const void *obj) {
      return ((::TMatlab*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_TMatlab(void *p) {
      return  p ? new(p) ::TMatlab : new ::TMatlab;
   }
   static void *newArray_TMatlab(Long_t size) {
      return new ::TMatlab[size];
   }
   // Wrapper around operator delete
   static void delete_TMatlab(void *p) {
      delete ((::TMatlab*)p);
   }
   static void deleteArray_TMatlab(void *p) {
      delete [] ((::TMatlab*)p);
   }
   static void destruct_TMatlab(void *p) {
      typedef ::TMatlab current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TMatlab

//______________________________________________________________________________
void TmxArray::Streamer(TBuffer &R__b)
{
   // Stream an object of class TmxArray.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TNamed::Streamer(R__b);
      R__b >> fMymx;
      R__b.CheckByteCount(R__s, R__c, TmxArray::IsA());
   } else {
      R__c = R__b.WriteVersion(TmxArray::IsA(), kTRUE);
      TNamed::Streamer(R__b);
      R__b << fMymx;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TmxArray::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TmxArray.

      TClass *R__cl = TmxArray::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fMymx", &fMymx);
      R__insp.Inspect(R__cl, R__parent, "*fmxArray", &fmxArray);
      TNamed::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TmxArray_IsA(const void *obj) {
      return ((::TmxArray*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_TmxArray(void *p) {
      return  p ? new(p) ::TmxArray : new ::TmxArray;
   }
   static void *newArray_TmxArray(Long_t size) {
      return new ::TmxArray[size];
   }
   // Wrapper around operator delete
   static void delete_TmxArray(void *p) {
      delete ((::TmxArray*)p);
   }
   static void deleteArray_TmxArray(void *p) {
      delete [] ((::TmxArray*)p);
   }
   static void destruct_TmxArray(void *p) {
      typedef ::TmxArray current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TmxArray

/********************************************************
* MatlabDict.cpp
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableMatlabDict();

extern "C" void G__set_cpp_environmentMatlabDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TMatlab.h");
  G__add_compiledheader("TmxArray.h");
  G__cpp_reset_tagtableMatlabDict();
}
class G__MatlabDictdOcpp_tag {};

void* operator new(size_t size,G__MatlabDictdOcpp_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__MatlabDictdOcpp_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_MatlabDictdOcpp() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevMatlabDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TmxArray */
static int G__MatlabDict_210_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TmxArray *p=NULL;
   if(G__getaryconstruct()) p=new TmxArray[G__getaryconstruct()];
   else                    p=new TmxArray;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__MatlabDictLN_TmxArray);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TmxArray *p=NULL;
      p = new TmxArray((const char*)G__int(libp->para[0]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__MatlabDictLN_TmxArray);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TmxArray *p=NULL;
      p = new TmxArray((void*)G__int(libp->para[0]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__MatlabDictLN_TmxArray);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Set((TDSPVector*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Set((TDSPMatrix*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        const TmxArray& obj=((TmxArray*)(G__getstructoffset()))->operator=(*(TDSPVector*)libp->para[0].ref);
         result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        const TmxArray& obj=((TmxArray*)(G__getstructoffset()))->operator=(*(TDSPMatrix*)libp->para[0].ref);
         result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,89,(long)((TmxArray*)(G__getstructoffset()))->Getmx());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Setmx((void*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->Get((TDSPMatrix*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 1:
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->Get((TDSPVector*)G__int(libp->para[0])));
      break;
   case 0:
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->Get());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((TmxArray*)(G__getstructoffset()))->IsString());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,67,(long)((TmxArray*)(G__getstructoffset()))->GetString((char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,67,(long)((TmxArray*)(G__getstructoffset()))->GetString((char*)G__int(libp->para[0])));
      break;
   case 0:
   G__letint(result7,67,(long)((TmxArray*)(G__getstructoffset()))->GetString());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->GetRow((Int_t)G__int(libp->para[0]),(TDSPVector*)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->GetRow((Int_t)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->GetColumn((Int_t)G__int(libp->para[0]),(TDSPVector*)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((TmxArray*)(G__getstructoffset()))->GetColumn((Int_t)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TmxArray*)(G__getstructoffset()))->GetN());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TmxArray*)(G__getstructoffset()))->GetM());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TmxArray*)(G__getstructoffset()))->GetCols());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TmxArray*)(G__getstructoffset()))->GetRows());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->SetName((const char*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)((TmxArray*)(G__getstructoffset()))->GetName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Print();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Clean();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Detach();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        TComplex *pobj,xobj=((TmxArray*)(G__getstructoffset()))->Element((Int_t)G__int(libp->para[0]));
        pobj=new TComplex(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      {
        TComplex *pobj,xobj=((TmxArray*)(G__getstructoffset()))->operator()((Int_t)G__int(libp->para[0]));
        pobj=new TComplex(xobj);
        result7->obj.i=(long)((void*)pobj); result7->ref=result7->obj.i;
        G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TmxArray::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TmxArray::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TmxArray::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TmxArray::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TmxArray*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_3_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_4_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TmxArray*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_5_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TmxArray::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_6_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TmxArray::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_7_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TmxArray::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_210_8_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TmxArray::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MatlabDict_210_9_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TmxArray *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TmxArray(*(TmxArray*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__MatlabDictLN_TmxArray);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TmxArray G__TTmxArray;
static int G__MatlabDict_210_0_4(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TmxArray *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TmxArray *)((G__getstructoffset())+sizeof(TmxArray)*i);
   else  delete (TmxArray *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TMatlab */
static int G__MatlabDict_215_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TMatlab *p=NULL;
   if(G__getaryconstruct()) p=new TMatlab[G__getaryconstruct()];
   else                    p=new TMatlab;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__MatlabDictLN_TMatlab);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TMatlab::GlobalEngine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
  G__va_arg_buf G__va_arg_bufobj;
  G__va_arg_put(&G__va_arg_bufobj,libp,1);
      G__letint(result7,103,(long)((TMatlab*)(G__getstructoffset()))->Eval((const char*)G__int(libp->para[0]),G__va_arg_bufobj));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
  G__va_arg_buf G__va_arg_bufobj;
  G__va_arg_put(&G__va_arg_bufobj,libp,1);
      G__letint(result7,103,(long)((TMatlab*)(G__getstructoffset()))->EvalString((const char*)G__int(libp->para[0]),G__va_arg_bufobj));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__letint(result7,105,(long)((TMatlab*)(G__getstructoffset()))->OutputBuffer((char*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7,105,(long)((TMatlab*)(G__getstructoffset()))->OutputBuffer((char*)G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7,105,(long)((TMatlab*)(G__getstructoffset()))->OutputBuffer());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((TMatlab*)(G__getstructoffset()))->Put((TmxArray*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
   G__letint(result7,85,(long)((TMatlab*)(G__getstructoffset()))->Get((const char*)G__int(libp->para[0]),(TmxArray*)G__int(libp->para[1])));
      break;
   case 1:
   G__letint(result7,85,(long)((TMatlab*)(G__getstructoffset()))->Get((const char*)G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TMatlab::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TMatlab::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TMatlab::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TMatlab::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TMatlab*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TMatlab*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TMatlab*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TMatlab*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TMatlab::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TMatlab::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TMatlab::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MatlabDict_215_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TMatlab::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MatlabDict_215_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TMatlab *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TMatlab(*(TMatlab*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__MatlabDictLN_TMatlab);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMatlab G__TTMatlab;
static int G__MatlabDict_215_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TMatlab *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TMatlab *)((G__getstructoffset())+sizeof(TMatlab)*i);
   else  delete (TMatlab *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TmxArray */

/* TMatlab */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncMatlabDict {
 public:
  G__Sizep2memfuncMatlabDict() {p=&G__Sizep2memfuncMatlabDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncMatlabDict::*p)();
};

size_t G__get_sizep2memfuncMatlabDict()
{
  G__Sizep2memfuncMatlabDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceMatlabDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__MatlabDictLN_TmxArray))) {
     TmxArray *G__Lderived;
     G__Lderived=(TmxArray*)0x1000;
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),G__get_linked_tagnum(&G__MatlabDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),G__get_linked_tagnum(&G__MatlabDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab))) {
     TMatlab *G__Lderived;
     G__Lderived=(TMatlab*)0x1000;
     {
       TQQObject *G__Lpbase=(TQQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),G__get_linked_tagnum(&G__MatlabDictLN_TQQObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),G__get_linked_tagnum(&G__MatlabDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),G__get_linked_tagnum(&G__MatlabDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObjSender *G__Lpbase=(TQObjSender*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),G__get_linked_tagnum(&G__MatlabDictLN_TQObjSender),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),G__get_linked_tagnum(&G__MatlabDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableMatlabDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TmxArray */
static void G__setup_memvarTmxArray(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MatlabDictLN_TmxArray));
   { TmxArray *p; p=(TmxArray*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fMymx=",0,"is that my array ?");
   G__memvar_setup((void*)NULL,89,0,0,-1,-1,-1,2,"fmxArray=",0,"!  ");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__MatlabDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TMatlab */
static void G__setup_memvarTMatlab(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab));
   { TMatlab *p; p=(TMatlab*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,89,0,0,-1,-1,-1,2,"fEngine=",0,"!");
   G__memvar_setup((void*)NULL,67,0,0,-1,-1,-1,2,"fOutputBuffer=",0,"!");
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"fEvalReturn=",0,"the Error Return Code of the last evaluation");
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__MatlabDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarMatlabDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTmxArray(void) {
   /* TmxArray */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MatlabDictLN_TmxArray));
   G__memfunc_setup("TmxArray",824,G__MatlabDict_210_0_0,105,G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TmxArray",824,G__MatlabDict_210_1_0,105,G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,0,1,1,1,0,"C - - 10 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TmxArray",824,G__MatlabDict_210_2_0,105,G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,0,1,1,1,0,"Y - - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Set",300,G__MatlabDict_210_4_0,121,-1,-1,0,1,1,1,0,"U 'TDSPVector' - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Set",300,G__MatlabDict_210_5_0,121,-1,-1,0,1,1,1,0,"U 'TDSPMatrix' - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("operator=",937,G__MatlabDict_210_6_0,117,G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,1,1,1,1,0,"u 'TDSPVector' - 1 - x",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("operator=",937,G__MatlabDict_210_7_0,117,G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,1,1,1,1,0,"u 'TDSPMatrix' - 1 - x",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Getmx",517,G__MatlabDict_210_8_0,89,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Setmx",529,G__MatlabDict_210_9_0,121,-1,-1,0,1,1,1,0,"Y - - 0 - m",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Get",288,G__MatlabDict_210_0_1,85,G__get_linked_tagnum(&G__MatlabDictLN_TDSPMatrix),-1,0,1,1,1,0,"U 'TDSPMatrix' - 0 - s",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Get",288,G__MatlabDict_210_1_1,85,G__get_linked_tagnum(&G__MatlabDictLN_TDSPVector),-1,0,1,1,1,0,"U 'TDSPVector' - 0 NULL s",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsString",819,G__MatlabDict_210_2_1,103,-1,G__defined_typename("Bool_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetString",919,G__MatlabDict_210_3_1,67,-1,-1,0,2,1,1,0,
"C - - 0 NULL buf i - 'Int_t' 0 0 buflen",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetRow",600,G__MatlabDict_210_4_1,85,G__get_linked_tagnum(&G__MatlabDictLN_TDSPVector),-1,0,2,1,1,0,
"i - 'Int_t' 0 - r U 'TDSPVector' - 0 NULL row",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetColumn",910,G__MatlabDict_210_5_1,85,G__get_linked_tagnum(&G__MatlabDictLN_TDSPVector),-1,0,2,1,1,0,
"i - 'Int_t' 0 - r U 'TDSPVector' - 0 NULL row",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetN",366,G__MatlabDict_210_6_1,105,-1,G__defined_typename("Int_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetM",365,G__MatlabDict_210_7_1,105,-1,G__defined_typename("Int_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetCols",689,G__MatlabDict_210_8_1,105,-1,G__defined_typename("Int_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetRows",715,G__MatlabDict_210_9_1,105,-1,G__defined_typename("Int_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetName",685,G__MatlabDict_210_0_2,121,-1,-1,0,1,1,1,0,"C - - 10 - -",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("GetName",673,G__MatlabDict_210_1_2,67,-1,-1,0,0,1,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Print",525,G__MatlabDict_210_2_2,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Clean",483,G__MatlabDict_210_3_2,121,-1,-1,0,0,1,1,0,"","/< Cleanup - remove the fmxarray if alloced by me ",(void*)NULL,0);
   G__memfunc_setup("Detach",585,G__MatlabDict_210_4_2,121,-1,-1,0,0,1,1,0,"","/< Detach the mxArray - is necessary for use in return arguments of mex-files",(void*)NULL,0);
   G__memfunc_setup("Element",714,G__MatlabDict_210_5_2,117,G__get_linked_tagnum(&G__MatlabDictLN_TComplex),-1,0,1,1,1,0,"i - 'Int_t' 0 - index",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("operator()",957,G__MatlabDict_210_6_2,117,G__get_linked_tagnum(&G__MatlabDictLN_TComplex),-1,0,1,1,1,0,"i - 'Int_t' 0 - index",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__MatlabDict_210_7_2,85,G__get_linked_tagnum(&G__MatlabDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__MatlabDict_210_8_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__MatlabDict_210_9_2,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__MatlabDict_210_0_3,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__MatlabDict_210_1_3,85,G__get_linked_tagnum(&G__MatlabDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__MatlabDict_210_2_3,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__MatlabDict_210_3_3,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MatlabDict_210_4_3,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__MatlabDict_210_5_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__MatlabDict_210_6_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__MatlabDict_210_7_3,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__MatlabDict_210_8_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("TmxArray",824,G__MatlabDict_210_9_3,(int)('i'),G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,0,1,1,1,0,"u 'TmxArray' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TmxArray",950,G__MatlabDict_210_0_4,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTMatlab(void) {
   /* TMatlab */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab));
   G__memfunc_setup("TMatlab",677,G__MatlabDict_215_0_0,105,G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GlobalEngine",1191,G__MatlabDict_215_2_0,85,G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Eval",392,G__MatlabDict_215_3_0,103,-1,G__defined_typename("Bool_t"),0,1,8,1,0,"C - - 10 - va_(fmt)",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("EvalString",1023,G__MatlabDict_215_4_0,103,-1,G__defined_typename("Bool_t"),0,1,8,1,0,"C - - 10 - va_(fmt)",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("OutputBuffer",1259,G__MatlabDict_215_5_0,105,-1,G__defined_typename("Int_t"),0,2,1,1,0,
"C - - 0 NULL buffer i - 'Int_t' 0 2048 buflen",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Put",313,G__MatlabDict_215_6_0,105,-1,G__defined_typename("Int_t"),0,1,1,1,0,"U 'TmxArray' - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Get",288,G__MatlabDict_215_7_0,85,G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),-1,0,2,1,1,0,
"C - - 10 - name U 'TmxArray' - 0 NULL a",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__MatlabDict_215_8_0,85,G__get_linked_tagnum(&G__MatlabDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__MatlabDict_215_9_0,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__MatlabDict_215_0_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__MatlabDict_215_1_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__MatlabDict_215_2_1,85,G__get_linked_tagnum(&G__MatlabDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__MatlabDict_215_3_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__MatlabDict_215_4_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MatlabDict_215_5_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__MatlabDict_215_6_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__MatlabDict_215_7_1,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__MatlabDict_215_8_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__MatlabDict_215_9_1,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("TMatlab",677,G__MatlabDict_215_0_2,(int)('i'),G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),-1,0,1,1,1,0,"u 'TMatlab' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TMatlab",803,G__MatlabDict_215_1_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncMatlabDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
   G__memvar_setup((void*)(&gMatlab),85,0,0,G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),-1,-1,1,"gMatlab=",0,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalMatlabDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcMatlabDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__MatlabDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TQQObject = { "TQQObject" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TComplex = { "TComplex" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TmxArray = { "TmxArray" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TDSPVector = { "TDSPVector" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TDSPMatrix = { "TDSPMatrix" , 99 , -1 };
G__linked_taginfo G__MatlabDictLN_TMatlab = { "TMatlab" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableMatlabDict() {
  G__MatlabDictLN_TClass.tagnum = -1 ;
  G__MatlabDictLN_TBuffer.tagnum = -1 ;
  G__MatlabDictLN_TMemberInspector.tagnum = -1 ;
  G__MatlabDictLN_TObject.tagnum = -1 ;
  G__MatlabDictLN_TNamed.tagnum = -1 ;
  G__MatlabDictLN_TQObject.tagnum = -1 ;
  G__MatlabDictLN_TQObjSender.tagnum = -1 ;
  G__MatlabDictLN_TQQObject.tagnum = -1 ;
  G__MatlabDictLN_TComplex.tagnum = -1 ;
  G__MatlabDictLN_TmxArray.tagnum = -1 ;
  G__MatlabDictLN_TDSPVector.tagnum = -1 ;
  G__MatlabDictLN_TDSPMatrix.tagnum = -1 ;
  G__MatlabDictLN_TMatlab.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableMatlabDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__MatlabDictLN_TClass);
   G__get_linked_tagnum(&G__MatlabDictLN_TBuffer);
   G__get_linked_tagnum(&G__MatlabDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__MatlabDictLN_TObject);
   G__get_linked_tagnum(&G__MatlabDictLN_TNamed);
   G__get_linked_tagnum(&G__MatlabDictLN_TQObject);
   G__get_linked_tagnum(&G__MatlabDictLN_TQObjSender);
   G__get_linked_tagnum(&G__MatlabDictLN_TQQObject);
   G__get_linked_tagnum(&G__MatlabDictLN_TComplex);
   G__tagtable_setup(G__get_linked_tagnum(&G__MatlabDictLN_TmxArray),sizeof(TmxArray),-1,64768,(char*)NULL,G__setup_memvarTmxArray,G__setup_memfuncTmxArray);
   G__get_linked_tagnum(&G__MatlabDictLN_TDSPVector);
   G__get_linked_tagnum(&G__MatlabDictLN_TDSPMatrix);
   G__tagtable_setup(G__get_linked_tagnum(&G__MatlabDictLN_TMatlab),sizeof(TMatlab),-1,62720,(char*)NULL,G__setup_memvarTMatlab,G__setup_memfuncTMatlab);
}
extern "C" void G__cpp_setupMatlabDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupMatlabDict()");
  G__set_cpp_environmentMatlabDict();
  G__cpp_setup_tagtableMatlabDict();

  G__cpp_setup_inheritanceMatlabDict();

  G__cpp_setup_typetableMatlabDict();

  G__cpp_setup_memvarMatlabDict();

  G__cpp_setup_memfuncMatlabDict();
  G__cpp_setup_globalMatlabDict();
  G__cpp_setup_funcMatlabDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncMatlabDict();
  return;
}
class G__cpp_setup_initMatlabDict {
  public:
    G__cpp_setup_initMatlabDict() { G__add_setup_func("MatlabDict",(G__incsetup)(&G__cpp_setupMatlabDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initMatlabDict() { G__remove_setup_func("MatlabDict"); }
};
G__cpp_setup_initMatlabDict G__cpp_setup_initializerMatlabDict;

