//
// File generated by rootcint at Fri Apr 23 11:57:57 2004.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

#include "TGObjectsDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "RtypesImp.h"

#include "TVectorProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void TGControlList_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TGControlList_IsA(const void*);
   static void delete_TGControlList(void *p);
   static void deleteArray_TGControlList(void *p);
   static void destruct_TGControlList(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const TGControlList*)
   {
      TGControlList *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("TGControlList", TGControlList::Class_Version(), "TGControlList.h", 50,
                  typeid(TGControlList), DefineBehavior(ptr, ptr),
                  &::TGControlList::Dictionary, &TGControlList_IsA, 0,
                  sizeof(TGControlList) );
      instance.SetDelete(&delete_TGControlList);
      instance.SetDeleteArray(&deleteArray_TGControlList);
      instance.SetDestructor(&destruct_TGControlList);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const TGControlList*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

namespace ROOT {
   void TGTabDialog_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TGTabDialog_IsA(const void*);
   static void delete_TGTabDialog(void *p);
   static void deleteArray_TGTabDialog(void *p);
   static void destruct_TGTabDialog(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const TGTabDialog*)
   {
      TGTabDialog *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("TGTabDialog", TGTabDialog::Class_Version(), "TGTabDialog.h", 31,
                  typeid(TGTabDialog), DefineBehavior(ptr, ptr),
                  &::TGTabDialog::Dictionary, &TGTabDialog_IsA, 0,
                  sizeof(TGTabDialog) );
      instance.SetDelete(&delete_TGTabDialog);
      instance.SetDeleteArray(&deleteArray_TGTabDialog);
      instance.SetDestructor(&destruct_TGTabDialog);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const TGTabDialog*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *TGControlList::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TGControlList::Class_Name()
{
   return "TGControlList";
}

//______________________________________________________________________________
const char *TGControlList::ImplFileName()
{
   return ROOT::GenerateInitInstance((const TGControlList*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TGControlList::ImplFileLine()
{
   return ROOT::GenerateInitInstance((const TGControlList*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TGControlList::Dictionary()
{
   fgIsA = ROOT::GenerateInitInstance((const TGControlList*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TGControlList::Class()
{
   if (!fgIsA) fgIsA = ROOT::GenerateInitInstance((const TGControlList*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TGTabDialog::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TGTabDialog::Class_Name()
{
   return "TGTabDialog";
}

//______________________________________________________________________________
const char *TGTabDialog::ImplFileName()
{
   return ROOT::GenerateInitInstance((const TGTabDialog*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TGTabDialog::ImplFileLine()
{
   return ROOT::GenerateInitInstance((const TGTabDialog*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TGTabDialog::Dictionary()
{
   fgIsA = ROOT::GenerateInitInstance((const TGTabDialog*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TGTabDialog::Class()
{
   if (!fgIsA) fgIsA = ROOT::GenerateInitInstance((const TGTabDialog*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TGControlList::Streamer(TBuffer &R__b)
{
   // Stream an object of class TGControlList.

   TGListTree::Streamer(R__b);
}

//______________________________________________________________________________
void TGControlList::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TGControlList.

      TClass *R__cl = TGControlList::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fEvent", &fEvent);
      TGListTree::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TGControlList_IsA(const void *obj) {
      return ((::TGControlList*)obj)->IsA();
   }
   // Wrapper around operator delete
   static void delete_TGControlList(void *p) {
      delete ((::TGControlList*)p);
   }
   static void deleteArray_TGControlList(void *p) {
      delete [] ((::TGControlList*)p);
   }
   static void destruct_TGControlList(void *p) {
      typedef ::TGControlList current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TGControlList

//______________________________________________________________________________
void TGTabDialog::Streamer(TBuffer &R__b)
{
   // Stream an object of class TGTabDialog.

   TGTransientFrame::Streamer(R__b);
}

//______________________________________________________________________________
void TGTabDialog::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TGTabDialog.

      TClass *R__cl = TGTabDialog::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fMain", &fMain);
      R__insp.Inspect(R__cl, R__parent, "*fBottomFrame", &fBottomFrame);
      R__insp.Inspect(R__cl, R__parent, "*fL1", &fL1);
      R__insp.Inspect(R__cl, R__parent, "*fL2", &fL2);
      R__insp.Inspect(R__cl, R__parent, "*fListOfTabs", &fListOfTabs);
      R__insp.Inspect(R__cl, R__parent, "*fOkButton", &fOkButton);
      R__insp.Inspect(R__cl, R__parent, "*fCancelButton", &fCancelButton);
      R__insp.Inspect(R__cl, R__parent, "*fTab", &fTab);
      TGTransientFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TGTabDialog_IsA(const void *obj) {
      return ((::TGTabDialog*)obj)->IsA();
   }
   // Wrapper around operator delete
   static void delete_TGTabDialog(void *p) {
      delete ((::TGTabDialog*)p);
   }
   static void deleteArray_TGTabDialog(void *p) {
      delete [] ((::TGTabDialog*)p);
   }
   static void destruct_TGTabDialog(void *p) {
      typedef ::TGTabDialog current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TGTabDialog

/********************************************************
* TGObjectsDict.cpp
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableTGObjectsDict();

extern "C" void G__set_cpp_environmentTGObjectsDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TGControlList.h");
  G__add_compiledheader("TGTabDialog.h");
  G__cpp_reset_tagtableTGObjectsDict();
}
class G__TGObjectsDictdOcpp_tag {};

void* operator new(size_t size,G__TGObjectsDictdOcpp_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__TGObjectsDictdOcpp_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_TGObjectsDictdOcpp() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevTGObjectsDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TGControlList */
static int G__TGObjectsDict_243_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,103,(long)((TGControlList*)(G__getstructoffset()))->HandleButton((Event_t*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->ToggleItem((TGListTreeItem*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->ClickItem((TGListTreeItem*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->OpenContextMenu((TGListTreeItem*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TGControlList *p=NULL;
   switch(libp->paran) {
   case 4:
      p = new TGControlList(
(TGWindow*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      p = new TGControlList(
(TGWindow*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      break;
   case 2:
      p = new TGControlList((TGWindow*)G__int(libp->para[0]),(UInt_t)G__int(libp->para[1]));
      break;
   case 1:
      p = new TGControlList((TGWindow*)G__int(libp->para[0]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TGControlList*)(G__getstructoffset()))->UserData((TGListTreeItem*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->ContextMenu((TGListTreeItem*)G__int(libp->para[0]),(TGPopupMenu*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->SetObject((TGListTreeItem*)G__int(libp->para[0]),(void*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,89,(long)((TGControlList*)(G__getstructoffset()))->GetObject((TGListTreeItem*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TGControlList*)(G__getstructoffset()))->GetClient());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TGControlList::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TGControlList::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TGControlList::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TGControlList::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TGControlList*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGControlList*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TGControlList::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TGControlList::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TGControlList::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_243_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TGControlList::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TGObjectsDict_243_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TGControlList *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TGControlList(*(TGControlList*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TGControlList G__TTGControlList;
static int G__TGObjectsDict_243_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TGControlList *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TGControlList *)((G__getstructoffset())+sizeof(TGControlList)*i);
   else  delete (TGControlList *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TGTabDialog */
static int G__TGObjectsDict_259_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TGTabDialog*)(G__getstructoffset()))->GetListOfTabs());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((TGTabDialog*)(G__getstructoffset()))->GetTab());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TGTabDialog *p=NULL;
   switch(libp->paran) {
   case 5:
      p = new TGTabDialog(
(const TGWindow*)G__int(libp->para[0]),(const TGWindow*)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3])
,(UInt_t)G__int(libp->para[4]));
      break;
   case 4:
      p = new TGTabDialog(
(const TGWindow*)G__int(libp->para[0]),(const TGWindow*)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]),(UInt_t)G__int(libp->para[3]));
      break;
   case 3:
      p = new TGTabDialog(
(const TGWindow*)G__int(libp->para[0]),(const TGWindow*)G__int(libp->para[1])
,(UInt_t)G__int(libp->para[2]));
      break;
   case 2:
      p = new TGTabDialog((const TGWindow*)G__int(libp->para[0]),(const TGWindow*)G__int(libp->para[1]));
      break;
   }
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->DrawDialog();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->Ok();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->Apply();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->Cancel();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->CloseWindow();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->HandlePopup((Int_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TGTabDialog::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TGTabDialog::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TGTabDialog::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TGTabDialog::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TGTabDialog*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TGTabDialog*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TGTabDialog::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TGTabDialog::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TGTabDialog::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TGObjectsDict_259_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TGTabDialog::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TGObjectsDict_259_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TGTabDialog *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TGTabDialog(*(TGTabDialog*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TGTabDialog G__TTGTabDialog;
static int G__TGObjectsDict_259_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TGTabDialog *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TGTabDialog *)((G__getstructoffset())+sizeof(TGTabDialog)*i);
   else  delete (TGTabDialog *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TGControlList */

/* TGTabDialog */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTGObjectsDict {
 public:
  G__Sizep2memfuncTGObjectsDict() {p=&G__Sizep2memfuncTGObjectsDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTGObjectsDict::*p)();
};

size_t G__get_sizep2memfuncTGObjectsDict()
{
  G__Sizep2memfuncTGObjectsDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTGObjectsDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList))) {
     TGControlList *G__Lderived;
     G__Lderived=(TGControlList*)0x1000;
     {
       TGListTree *G__Lpbase=(TGListTree*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TGListTree),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGContainer *G__Lpbase=(TGContainer*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TGContainer),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),G__get_linked_tagnum(&G__TGObjectsDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog))) {
     TGTabDialog *G__Lderived;
     G__Lderived=(TGTabDialog*)0x1000;
     {
       TGTransientFrame *G__Lpbase=(TGTransientFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TGTransientFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),G__get_linked_tagnum(&G__TGObjectsDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTGObjectsDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Bool_t",103,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TGControlList */
static void G__setup_memvarTGControlList(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList));
   { TGControlList *p; p=(TGControlList*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_Event_t),-1,-1,4,"fEvent=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TGTabDialog */
static void G__setup_memvarTGTabDialog(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog));
   { TGTabDialog *p; p=(TGTabDialog*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,1,G__get_linked_tagnum(&G__TGObjectsDictLN_TGWindow),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TGCompositeFrame),-1,-1,4,"fBottomFrame=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TGLayoutHints),-1,-1,4,"fL1=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TGLayoutHints),-1,-1,4,"fL2=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TList),-1,-1,4,"fListOfTabs=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TGButton),-1,-1,4,"fOkButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TGButton),-1,-1,4,"fCancelButton=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TGTab),-1,-1,4,"fTab=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__TGObjectsDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTGObjectsDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTGControlList(void) {
   /* TGControlList */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList));
   G__memfunc_setup("HandleButton",1224,G__TGObjectsDict_243_0_0,103,-1,G__defined_typename("Bool_t"),0,1,1,1,0,"U 'Event_t' - 0 - -",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ToggleItem",1009,G__TGObjectsDict_243_1_0,121,-1,-1,0,2,1,1,0,
"U 'TGListTreeItem' - 0 - - i - 'Int_t' 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ClickItem",885,G__TGObjectsDict_243_2_0,121,-1,-1,0,2,1,1,0,
"U 'TGListTreeItem' - 0 - - i - 'Int_t' 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("OpenContextMenu",1548,G__TGObjectsDict_243_3_0,121,-1,-1,0,1,1,1,0,"U 'TGListTreeItem' - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TGControlList",1304,G__TGObjectsDict_243_4_0,105,G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),-1,0,4,1,1,0,
"U 'TGWindow' - 0 - parent h - 'UInt_t' 0 300 w "
"h - 'UInt_t' 0 150 h h - 'UInt_t' 0 0 o",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("UserData",793,G__TGObjectsDict_243_6_0,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlListItemUserData),-1,0,1,1,1,0,"U 'TGListTreeItem' - 0 - item",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ContextMenu",1146,G__TGObjectsDict_243_7_0,121,-1,-1,0,2,1,1,0,
"U 'TGListTreeItem' - 0 - - U 'TGPopupMenu' - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetObject",899,G__TGObjectsDict_243_8_0,121,-1,-1,0,2,1,1,0,
"U 'TGListTreeItem' - 0 - - Y - - 0 - -",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetObject",887,G__TGObjectsDict_243_9_0,89,-1,-1,0,1,1,1,0,"U 'TGListTreeItem' - 0 - i",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetClient",895,G__TGObjectsDict_243_0_1,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TGClient),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__TGObjectsDict_243_1_1,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__TGObjectsDict_243_2_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__TGObjectsDict_243_3_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__TGObjectsDict_243_4_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__TGObjectsDict_243_5_1,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__TGObjectsDict_243_6_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__TGObjectsDict_243_7_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TGObjectsDict_243_8_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__TGObjectsDict_243_9_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__TGObjectsDict_243_0_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__TGObjectsDict_243_1_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__TGObjectsDict_243_2_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("TGControlList",1304,G__TGObjectsDict_243_3_2,(int)('i'),G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),-1,0,1,1,1,0,"u 'TGControlList' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TGControlList",1430,G__TGObjectsDict_243_4_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTGTabDialog(void) {
   /* TGTabDialog */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog));
   G__memfunc_setup("GetListOfTabs",1275,G__TGObjectsDict_259_0_0,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TList),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetTab",567,G__TGObjectsDict_259_1_0,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TGTab),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("TGTabDialog",1026,G__TGObjectsDict_259_2_0,105,G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),-1,0,5,1,1,0,
"U 'TGWindow' - 10 - p U 'TGWindow' - 10 - main "
"h - 'UInt_t' 0 500 w h - 'UInt_t' 0 300 h "
"h - 'UInt_t' 0 kVerticalFrame options",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DrawDialog",990,G__TGObjectsDict_259_3_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Ok",186,G__TGObjectsDict_259_5_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Apply",518,G__TGObjectsDict_259_6_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Cancel",582,G__TGObjectsDict_259_7_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("CloseWindow",1134,G__TGObjectsDict_259_8_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("HandlePopup",1120,G__TGObjectsDict_259_9_0,121,-1,-1,0,1,1,1,0,"i - 'Int_t' 0 - -",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Class",502,G__TGObjectsDict_259_0_1,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__TGObjectsDict_259_1_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__TGObjectsDict_259_2_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__TGObjectsDict_259_3_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__TGObjectsDict_259_4_1,85,G__get_linked_tagnum(&G__TGObjectsDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__TGObjectsDict_259_5_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__TGObjectsDict_259_6_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TGObjectsDict_259_7_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__TGObjectsDict_259_8_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__TGObjectsDict_259_9_1,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__TGObjectsDict_259_0_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__TGObjectsDict_259_1_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("TGTabDialog",1026,G__TGObjectsDict_259_2_2,(int)('i'),G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),-1,0,1,1,1,0,"u 'TGTabDialog' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TGTabDialog",1152,G__TGObjectsDict_259_3_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTGObjectsDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTGObjectsDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTGObjectsDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TGObjectsDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_Event_t = { "Event_t" , 115 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGClient = { "TGClient" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGLayoutHints = { "TGLayoutHints" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGTransientFrame = { "TGTransientFrame" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGContainer = { "TGContainer" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGPopupMenu = { "TGPopupMenu" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGControlListItemUserData = { "TGControlListItemUserData" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGControlList = { "TGControlList" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGButton = { "TGButton" , 99 , -1 };
G__linked_taginfo G__TGObjectsDictLN_TGTabDialog = { "TGTabDialog" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTGObjectsDict() {
  G__TGObjectsDictLN_TClass.tagnum = -1 ;
  G__TGObjectsDictLN_TBuffer.tagnum = -1 ;
  G__TGObjectsDictLN_TMemberInspector.tagnum = -1 ;
  G__TGObjectsDictLN_TObject.tagnum = -1 ;
  G__TGObjectsDictLN_TList.tagnum = -1 ;
  G__TGObjectsDictLN_Event_t.tagnum = -1 ;
  G__TGObjectsDictLN_TGClient.tagnum = -1 ;
  G__TGObjectsDictLN_TGObject.tagnum = -1 ;
  G__TGObjectsDictLN_TGWindow.tagnum = -1 ;
  G__TGObjectsDictLN_TQObject.tagnum = -1 ;
  G__TGObjectsDictLN_TGFrame.tagnum = -1 ;
  G__TGObjectsDictLN_TGCompositeFrame.tagnum = -1 ;
  G__TGObjectsDictLN_TGLayoutHints.tagnum = -1 ;
  G__TGObjectsDictLN_TGMainFrame.tagnum = -1 ;
  G__TGObjectsDictLN_TGTransientFrame.tagnum = -1 ;
  G__TGObjectsDictLN_TGContainer.tagnum = -1 ;
  G__TGObjectsDictLN_TGListTreeItem.tagnum = -1 ;
  G__TGObjectsDictLN_TGListTree.tagnum = -1 ;
  G__TGObjectsDictLN_TGPopupMenu.tagnum = -1 ;
  G__TGObjectsDictLN_TGControlListItemUserData.tagnum = -1 ;
  G__TGObjectsDictLN_TGControlList.tagnum = -1 ;
  G__TGObjectsDictLN_TGTab.tagnum = -1 ;
  G__TGObjectsDictLN_TGButton.tagnum = -1 ;
  G__TGObjectsDictLN_TGTabDialog.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTGObjectsDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__TGObjectsDictLN_TClass);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TBuffer);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TObject);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TList);
   G__get_linked_tagnum(&G__TGObjectsDictLN_Event_t);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGClient);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGObject);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGWindow);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TQObject);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGFrame);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGCompositeFrame);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGLayoutHints);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGMainFrame);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGTransientFrame);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGContainer);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGListTreeItem);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGListTree);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGPopupMenu);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlListItemUserData);
   G__tagtable_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGControlList),sizeof(TGControlList),-1,62464,(char*)NULL,G__setup_memvarTGControlList,G__setup_memfuncTGControlList);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGTab);
   G__get_linked_tagnum(&G__TGObjectsDictLN_TGButton);
   G__tagtable_setup(G__get_linked_tagnum(&G__TGObjectsDictLN_TGTabDialog),sizeof(TGTabDialog),-1,62464,(char*)NULL,G__setup_memvarTGTabDialog,G__setup_memfuncTGTabDialog);
}
extern "C" void G__cpp_setupTGObjectsDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTGObjectsDict()");
  G__set_cpp_environmentTGObjectsDict();
  G__cpp_setup_tagtableTGObjectsDict();

  G__cpp_setup_inheritanceTGObjectsDict();

  G__cpp_setup_typetableTGObjectsDict();

  G__cpp_setup_memvarTGObjectsDict();

  G__cpp_setup_memfuncTGObjectsDict();
  G__cpp_setup_globalTGObjectsDict();
  G__cpp_setup_funcTGObjectsDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTGObjectsDict();
  return;
}
class G__cpp_setup_initTGObjectsDict {
  public:
    G__cpp_setup_initTGObjectsDict() { G__add_setup_func("TGObjectsDict",(G__incsetup)(&G__cpp_setupTGObjectsDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTGObjectsDict() { G__remove_setup_func("TGObjectsDict"); }
};
G__cpp_setup_initTGObjectsDict G__cpp_setup_initializerTGObjectsDict;

