///////////////////////////////////////////////////////////////////
// Automatically generated by xml2ulxr v1.7.5.
//
// xml2ulxr is part of Ultra Lightweight XML RPC for C++.
// See also http://ulxmlrpcpp.sourceforge.net
//
// Intended for manual and persistent changes 
/////////////////////////////////////////////////

//#define ULXR_UNICODE_ONLY_HELPERS
#include <ulxmlrpcpp/ulxmlrpcpp.h> // always first

#include <ulxmlrpcpp/ulxr_value.h>
#include "UlxrIdlTestFuncs_ulxr_client.h"

// #include <ulxmlrpcpp/ulxr_response.h>
// #include <ulxmlrpcpp/ulxr_requester.h>
// #include <ulxmlrpcpp/ulxr_except.h>

// #include "UlxrIdlTestFuncs_ulxr_names.h"

