///////////////////////////////////////////////////////////////////
// Automatically generated by xml2ulxr v1.7.5.
//
// xml2ulxr is part of Ultra Lightweight XML RPC for C++.
// See also http://ulxmlrpcpp.sourceforge.net
//
// Intended for manual and persistent changes 
/////////////////////////////////////////////////

//#define ULXR_UNICODE_ONLY_HELPERS
#include <ulxmlrpcpp/ulxmlrpcpp.h> // always first

#include <ulxmlrpcpp/ulxr_value.h>
#include "UlxrIdlTestFuncs_ulxr_server.h"

#include <ulxmlrpcpp/ulxr_response.h>
#include <ulxmlrpcpp/ulxr_method_adder.h>
#include <ulxmlrpcpp/ulxr_signature.h>

#include "UlxrIdlTestFuncs_ulxr_names.h"


ulxr::MethodResponse
  UlxrIdlTestFuncs_funcs__free_function1_ovr0 (const ulxr::MethodCall &calldata);

ulxr::MethodResponse
  UlxrIdlTestFuncs_funcs__free_function1_ovr1 (const ulxr::MethodCall &calldata);

ulxr::MethodResponse
  UlxrIdlTestFuncs_inline_func__free_function2 (const ulxr::MethodCall &calldata);


void UlxrIdlTestFuncs_setupServerMethods(ulxr::MethodAdder &method_adder)
{
// mapped to: void funcs::free_function1(int i);   (there are overloaded methods)
  method_adder.addMethod(ulxr::make_method(&UlxrIdlTestFuncs_funcs__free_function1_ovr0),
                         ulxr::Void::getValueName(),
                         ULXR_CALLTO_UlxrIdlTestFuncs_funcs__free_function1_ovr0,
                         ulxr::Signature()
                           << ulxr::Integer::getValueName(),
                         ulxr_i18n(ULXR_PCHAR("Some descriptive comment about 'void funcs::free_function1(int i)'."))); // TODO adjust comment

// mapped to: long int funcs::free_function1(long int i, float f);   (there are overloaded methods)
  method_adder.addMethod(ulxr::make_method(&UlxrIdlTestFuncs_funcs__free_function1_ovr1),
                         ulxr::Integer::getValueName(),
                         ULXR_CALLTO_UlxrIdlTestFuncs_funcs__free_function1_ovr1,
                         ulxr::Signature()
                           << ulxr::Integer::getValueName()
                           << ulxr::Double::getValueName(),
                         ulxr_i18n(ULXR_PCHAR("Some descriptive comment about 'long int funcs::free_function1(long int i, float f)'."))); // TODO adjust comment

// mapped to: std::string * inline_func::free_function2(long int * i, float f);   (there are overloaded methods)
  method_adder.addMethod(ulxr::make_method(&UlxrIdlTestFuncs_inline_func__free_function2),
                         ulxr::RpcString::getValueName(),
                         ULXR_CALLTO_UlxrIdlTestFuncs_inline_func__free_function2,
                         ulxr::Signature()
                           << ulxr::Integer::getValueName()
                           << ulxr::Double::getValueName(),
                         ulxr_i18n(ULXR_PCHAR("Some descriptive comment about 'std::string * inline_func::free_function2(long int * i, float f)'."))); // TODO adjust comment
}

